//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkpoint
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> id_buses { get; set; }
    
        public virtual bus bus { get; set; }
    }
}
