//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cmt()
        {
            this.cmt11 = new HashSet<cmt>();
        }
    
        public int id { get; set; }
        public string cmt1 { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> parent_cmt_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmt> cmt11 { get; set; }
        public virtual cmt cmt2 { get; set; }
        public virtual guest_account guest_account { get; set; }
    }
}
