//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    
    public partial class GetTripDetails_Result1
    {
        public int trip_id { get; set; }
        public int trip_details_id { get; set; }
        public int vehicle_id { get; set; }
        public int buses_id { get; set; }
        public string start_point { get; set; }
        public string end_point { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<int> so_ghe_trong { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public string ten_xe { get; set; }
        public string anh_xe { get; set; }
        public string anh_nxe { get; set; }
        public string ten_nxe { get; set; }
    }
}
