//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int id { get; set; }
        public string tieu_de { get; set; }
        public string tom_tat { get; set; }
        public string hinh_anh { get; set; }
        public string noi_dung { get; set; }
        public System.DateTime thoi_gian_viet { get; set; }
        public string tac_gia { get; set; }
        public string link_seo { get; set; }
    }
}
