//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public System.Guid id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> guest_id { get; set; }
        public Nullable<int> trip_id { get; set; }
        public Nullable<double> total_money { get; set; }
        public string phone_number { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> date_success { get; set; }
        public Nullable<int> type_pay { get; set; }
        public Nullable<bool> status { get; set; }
        public string note { get; set; }
    
        public virtual guest_account guest_account { get; set; }
        public virtual trip trip { get; set; }
    }
}
