//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip_details
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.TimeSpan> time_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public Nullable<System.TimeSpan> time_end { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> trip_id { get; set; }
    
        public virtual trip trip { get; set; }
    }
}
