//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trip()
        {
            this.transactions = new HashSet<transaction>();
            this.trip_details = new HashSet<trip_details>();
        }
    
        public int id { get; set; }
        public string start_point { get; set; }
        public string end_point { get; set; }
        public Nullable<bool> status_confirm { get; set; }
        public Nullable<bool> status_update { get; set; }
        public Nullable<bool> status_delete { get; set; }
        public Nullable<int> id_discount { get; set; }
        public Nullable<int> vehicle_id { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<int> chair { get; set; }
        public string name { get; set; }
    
        public virtual discount discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction> transactions { get; set; }
        public virtual vehicle vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trip_details> trip_details { get; set; }
    }
}
